import { Metadata } from 'next'; // Updated import
import { Roboto, JetBrains_Mono } from 'next/font/google'; // Using available fonts
import './globals.css';

// Load fonts using Next.js font optimization
const roboto = Roboto({
  weight: ['400', '700'], // Specify the weights you want to use
  variable: '--font-roboto',
  subsets: ['latin'],
});

const jetBrainsMono = JetBrains_Mono({
  weight: ['400', '700'], // Specify the weights you want to use
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

// Set the metadata for the page
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${jetBrainsMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
